# Task 1

In [182]:
import pandas as pd

cars_df = pd.read_csv("cars.csv")

In [183]:
cars_df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

1. Horsepower was the wrong type and origin is suppose to be categories.

# Task 2

In [184]:
cars_df["horsepower"] = pd.to_numeric(cars_df["horsepower"], errors="coerce")
cars_df = cars_df.dropna()
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(4), int64(4), object(1)
memory usage: 30.6+ KB

# Task 3

In [185]:
X = cars_df.drop(columns=["car name", "mpg"])
y = cars_df["mpg"]

#It cannot be used as model input because it is not numeric

# Task 4

1. We are leaking the test data into the training data. Our model will give inaccurate data.

In [186]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#  Task 5

In [187]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

origin_encode = ohe.fit_transform(X_train[["origin"]])
test_encode = ohe.transform(X_test[['origin']])
origin_cols = ohe.get_feature_names_out()

origin_df = pd.DataFrame(origin_encode, columns=origin_cols, dtype=int)
X_train = pd.concat([X_train.drop(columns=['origin']), origin_df], axis=1)

In [192]:
X_train.head()

,cylinders,displacement,horsepower,weight,acceleration,model year,origin_1,origin_2
260,0.304862,0.284578,0.141429,0.754803,1.121759,0.494528,1.0,0.0
184,-0.873184,-0.535880,-0.329499,-0.493129,-0.228940,-0.057298,1.0,0.0
174,0.304862,-0.236655,-0.198685,-0.002530,-0.371118,-0.333211,0.0,0.0
64,1.482907,1.182255,1.187934,1.368052,-0.726565,-1.160950,1.0,0.0
344,-0.873184,-1.057113,-1.062052,-1.323099,0.304231,1.322266,NaN,NaN

In [189]:
test_df = pd.DataFrame(test_encode, columns=origin_cols, dtype=int)
X_test = pd.concat([X_test.drop(columns=['origin']), test_df], axis=1)

# Task 6

1. We are dropping origin_3. It does not matter because if its not 1 or 2 it has to be 3 and the same for all 3. 
2. It's different because this is perfectly multicollinear. We can tell the value of the third column based on the first 2.

In [190]:
X_train = X_train.drop(columns=['origin_3'])
X_test = X_test.drop(columns=['origin_3'])

# Task 7

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']] = ss.fit_transform(X_train[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']])
X_test[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']] = ss.transform(X_test[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']])

X_train