# Task 1

In [110]:
import pandas as pd

cars_df = pd.read_csv("cars.csv")

In [111]:
cars_df.loc[344]

mpg                       39.0
cylinders                    4
displacement              86.0
horsepower                  64
weight                    1875
acceleration              16.4
model year                  81
origin                       1
car name        plymouth champ
Name: 344, dtype: object

1. Horsepower was the wrong type and origin is suppose to be categories.

# Task 2

In [112]:
cars_df["horsepower"] = pd.to_numeric(cars_df["horsepower"], errors="coerce")
cars_df = cars_df.dropna()
cars_df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

# Task 3

In [113]:
X = cars_df.drop(columns=["car name", "mpg"])
y = cars_df["mpg"]

#It cannot be used as model input because it is not numeric

# Task 4

1. We are leaking the test data into the training data. Our model will give inaccurate data.

In [114]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

#  Task 5

In [115]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

origin_encode = ohe.fit_transform(X_train[["origin"]])
test_encode = ohe.transform(X_test[['origin']])
origin_cols = ohe.get_feature_names_out(['origin'])

origin_df = pd.DataFrame(origin_encode, columns=origin_cols, dtype=int)
X_train = pd.concat([X_train.drop(columns=['origin']).reset_index(), origin_df], axis=1)

In [116]:
X_train

,index,cylinders,displacement,horsepower,weight,acceleration,model year,origin_1,origin_2,origin_3
0,260,6,225.0,110.0,3620,18.7,78,1,0,0
1,184,4,140.0,92.0,2572,14.9,76,1,0,0
2,174,6,171.0,97.0,2984,14.5,75,1,0,0
3,64,8,318.0,150.0,4135,13.5,72,1,0,0
4,344,4,86.0,64.0,1875,16.4,81,1,0,0
...,...,...,...,...,...,...,...,...,...,...
308,72,8,304.0,150.0,3892,12.5,72,1,0,0
309,107,6,232.0,100.0,2789,15.0,73,1,0,0
310,272,4,151.0,85.0,2855,17.6,78,1,0,0
311,352,4,98.0,65.0,2380,20.7,81,1,0,0
312,103,8,400.0,150.0,4997,14.0,73,1,0,0

In [117]:
test_df = pd.DataFrame(test_encode, columns=origin_cols, dtype=int)
X_test = pd.concat([X_test.drop(columns=['origin']), test_df], axis=1)

# Task 6

1. We are dropping origin_3. It does not matter because if its not 1 or 2 it has to be 3 and the same for all 3. 
2. It's different because this is perfectly multicollinear. We can tell the value of the third column based on the first 2.

In [118]:
X_train = X_train.drop(columns=['origin_3'])
X_test = X_test.drop(columns=['origin_3'])

# Task 7

In [119]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']] = ss.fit_transform(X_train[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']])
X_test[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']] = ss.transform(X_test[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year']])

X_train

,index,cylinders,displacement,horsepower,weight,acceleration,model year,origin_1,origin_2
0,260,0.304862,0.284578,0.141429,0.754803,1.121759,0.494528,1,0
1,184,-0.873184,-0.535880,-0.329499,-0.493129,-0.228940,-0.057298,1,0
2,174,0.304862,-0.236655,-0.198685,-0.002530,-0.371118,-0.333211,1,0
3,64,1.482907,1.182255,1.187934,1.368052,-0.726565,-1.160950,1,0
4,344,-0.873184,-1.057113,-1.062052,-1.323099,0.304231,1.322266,1,0
...,...,...,...,...,...,...,...,...,...
308,72,1.482907,1.047121,1.187934,1.078694,-1.082012,-1.160950,1,0
309,107,0.304862,0.352145,-0.120198,-0.234731,-0.193395,-0.885037,1,0
310,272,-0.873184,-0.429703,-0.512637,-0.156140,0.730767,0.494528,1,0
311,352,-0.873184,-0.941283,-1.035889,-0.721758,1.832653,1.322266,1,0
312,103,1.482907,1.973756,1.187934,2.394500,-0.548842,-0.885037,1,0